dados = input('Digite algum caracter! ')
print('O caracter {} tem as seguintes características'.format(dados))
print('É do tipo primitivo {}'.format(type(dados)))
print('É numérico? {}'.format(dados.isnumeric()))
print('É alfanumérico? {}'.format(dados.isalnum()))
print('É somente espaços? {}'.format(dados.isspace()))
print('É somente letras? {}'.format(dados.isalpha()))
print('É somente letras maiúsculas? {}'.format(dados.isupper()))
print('É somente letras minúsculas? {}'.format(dados.islower()))